### ISSUE TITLE
Task assignment

### ISSUE THREAD

**Issue by principlebrothers** [principlebrothers/Excellent-Tasty-Meals#40]
## As far as the Excellent-Tasty-Meal project is concerned, only two people will be participating.
We are;
Ernest Anyewe Adonu - @principlebrothers 
Priscilla Oyebade - @OyePriscilla 

- Below is the link to the project
https://github.com/principlebrothers/Excellent-Tasty-Meals/projects/1

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @principlebrothers & @OyePriscilla, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principlebrothers** [comment]
Thank you for the review.
